baseURL = "https://zaimblog-669aa.web.app/"
# baseURL = "http://localhost:5000/"
languageCode = "en-us"
title = "PHP in the Wild"
theme = "hello-friend-ng"
enableInlineShortcodes = true
useRelativeCover = true
paginate = 5
images = ['android-chrome-256x256.png']

[author]
  name = "zaimazhar"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[params.logo]
  logoMark = "$"

[params]
  homeSubtitle = "I ride dragons with PHP, horses with JavaScript, and donkey with CSS"
  utama = "zaim."

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/zaimazhar/"

[[params.social]]
  name = "facebook"
  url = "https://www.facebook.com/muhammadzaim.azhar/"

[[params.social]]
  name = "github"
  url = "https://github.com/zaimazhar"

# And you can even create generic menu
[[menu.main]]
  identifier = "blog"
  name       = "blog"
  url        = "/posts"
  
[[menu.main]]
  identifier = "home"
  weight = "1"
  name       = "home"
  url        = "/"


# [[menu.main]]
#   identifier = "makan"
#   name       = "Makan"
#   url        = "/makan"